from zafkiel import Template
from zafkiel.ocr import Keyword

# 调度收益 -> 情报储备 Switch
DISPATCH_REWARD_INTELLIGENCE_RESERVE_SWITCH_ON = Template(r"DISPATCH_REWARD_INTELLIGENCE_RESERVE_SWITCH_ON.png", (-0.389, -0.199), rgb=True)

DISPATCH_REWARD_INTELLIGENCE_RESERVE_SWITCH_OFF = Template(r"DISPATCH_REWARD_INTELLIGENCE_RESERVE_SWITCH_OFF.png", (-0.414, -0.198), rgb=True)

# 调度收益 -> 资源生产 Switch
DISPATCH_REWARD_RESOURCE_PRODUCTION_SWITCH_OFF = Template(r"DISPATCH_REWARD_RESOURCE_PRODUCTION_SWITCH_OFF.png", (-0.401, -0.146),rgb=True)
DISPATCH_REWARD_RESOURCE_PRODUCTION_SWITCH_ON = Template(r"DISPATCH_REWARD_RESOURCE_PRODUCTION_SWITCH_ON.png", (-0.399, -0.146), rgb=True)